version: "3.8"
services:
    api:
        build:
            dockerfile: Dockerfile
            context: .
        depends_on: 
            - postgres
        environment: 
            DATABASE_URL: postgres://postgres:@postgres:5432/ideas
            NODE_ENV: development
            PORT: 3000
        ports:
            - "8080:3000"

    postgres:
        image: postgres:10.4
        ports:
            - "35000:5432"
        environment: 
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: 
            POSTGRES_DB: ideas